// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Models;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625121102_SeedMoreData")]
    partial class SeedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Models.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = "CNTT18-06",
                            ClassName = "CNTT 18-06",
                            FacultyId = "CNTT"
                        },
                        new
                        {
                            ClassId = "CNTT18-07",
                            ClassName = "CNTT 18-07",
                            FacultyId = "CNTT"
                        },
                        new
                        {
                            ClassId = "KT18-01",
                            ClassName = "Kinh tế 18-01",
                            FacultyId = "KT"
                        },
                        new
                        {
                            ClassId = "CK18-01",
                            ClassName = "Cơ khí 18-01",
                            FacultyId = "CK"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.CourseClass", b =>
                {
                    b.Property<string>("CourseClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentStudents")
                        .HasColumnType("int");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Schedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CourseClassId");

                    b.HasIndex("SubjectCode");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseClasses");

                    b.HasData(
                        new
                        {
                            CourseClassId = "LHP_CNPM_01",
                            CurrentStudents = 45,
                            MaxStudents = 50,
                            Schedule = "Thứ 3 (Ca 1)",
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Mở đăng ký",
                            SubjectCode = "CNPM_01",
                            TeacherId = "GV_001"
                        },
                        new
                        {
                            CourseClassId = "LHP_CSDL_02",
                            CurrentStudents = 50,
                            MaxStudents = 50,
                            Schedule = "Thứ 5 (Ca 2)",
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Đã đầy",
                            SubjectCode = "CSDL_01",
                            TeacherId = "GV_002"
                        },
                        new
                        {
                            CourseClassId = "LHP_LTW_01",
                            CurrentStudents = 0,
                            MaxStudents = 40,
                            Schedule = "Thứ 2 (Ca 3)",
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Chờ duyệt",
                            SubjectCode = "LTW_01",
                            TeacherId = "GV_003"
                        },
                        new
                        {
                            CourseClassId = "LHP_KTLT_01",
                            CurrentStudents = 2,
                            MaxStudents = 50,
                            Schedule = "Thứ 6 (Ca 1)",
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Mở đăng ký",
                            SubjectCode = "KTLT_01",
                            TeacherId = "GV_001"
                        },
                        new
                        {
                            CourseClassId = "LHP_MMT_01",
                            CurrentStudents = 1,
                            MaxStudents = 45,
                            Schedule = "Thứ 4 (Ca 3)",
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Mở đăng ký",
                            SubjectCode = "MMT_01",
                            TeacherId = "GV_002"
                        },
                        new
                        {
                            CourseClassId = "LHP_KTCT_01",
                            CurrentStudents = 0,
                            MaxStudents = 60,
                            Schedule = "Thứ 7 (Ca 2)",
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Mở đăng ký",
                            SubjectCode = "KTCT_01",
                            TeacherId = "GV_004"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Faculty", b =>
                {
                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            FacultyId = "CNTT",
                            FacultyName = "Công nghệ Thông tin"
                        },
                        new
                        {
                            FacultyId = "KT",
                            FacultyName = "Kinh tế"
                        },
                        new
                        {
                            FacultyId = "CK",
                            FacultyName = "Cơ khí"
                        },
                        new
                        {
                            FacultyId = "CB",
                            FacultyName = "Khoa Cơ bản"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Attendance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Final")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LetterGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Midterm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attendance = 9m,
                            Final = 8.5m,
                            LetterGrade = "B+",
                            Midterm = 8m,
                            Semester = "Học kỳ 2 - 2023",
                            StudentId = "18710205",
                            SubjectCode = "CNPM_01",
                            SubjectName = "Công nghệ phần mềm",
                            TotalScore = 8.4m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Attendance = 10m,
                            Final = 9m,
                            LetterGrade = "A",
                            Midterm = 9m,
                            Semester = "Học kỳ 2 - 2023",
                            StudentId = "18710205",
                            SubjectCode = "CSDL_01",
                            SubjectName = "Cơ sở dữ liệu",
                            TotalScore = 9.1m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Attendance = 8m,
                            Final = 6m,
                            LetterGrade = "C+",
                            Midterm = 7m,
                            Semester = "Học kỳ 2 - 2023",
                            StudentId = "18710204",
                            SubjectCode = "CNPM_01",
                            SubjectName = "Công nghệ phần mềm",
                            TotalScore = 6.5m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Attendance = 10m,
                            Final = 7.5m,
                            LetterGrade = "B+",
                            Midterm = 8.5m,
                            Semester = "Học kỳ 2 - 2023",
                            StudentId = "18710206",
                            SubjectCode = "TRR_01",
                            SubjectName = "Toán rời rạc",
                            TotalScore = 8.05m,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<string>("CourseClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("RegistrationId");

                    b.HasIndex("CourseClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            CourseClassId = "LHP_KTLT_01",
                            RegistrationDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Đã đăng ký",
                            StudentId = "18710205",
                            Year = 2024
                        },
                        new
                        {
                            RegistrationId = 2,
                            CourseClassId = "LHP_KTLT_01",
                            RegistrationDate = new DateTime(2024, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Đã đăng ký",
                            StudentId = "18710206",
                            Year = 2024
                        },
                        new
                        {
                            RegistrationId = 3,
                            CourseClassId = "LHP_MMT_01",
                            RegistrationDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "Học kỳ 1 - 2024",
                            Status = "Đã đăng ký",
                            StudentId = "18710205",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.Property<string>("MSSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hometown")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MSSV");

                    b.HasIndex("ClassId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            MSSV = "18710205",
                            ClassId = "CNTT18-06",
                            DateOfBirth = new DateTime(2000, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "trung@xxx.edu",
                            FacultyId = "CNTT",
                            FullName = "Nguyễn Quang Trung",
                            Gender = "Nam",
                            Hometown = "Hà Nội",
                            PasswordHash = "$2a$11$0v6jC.8f2d.1v.Q7L0.8o.9Q5i.4E1v2d6s.4f2d.1v.Q7L0.8o",
                            Status = "Đang học"
                        },
                        new
                        {
                            MSSV = "18710204",
                            ClassId = "CNTT18-06",
                            DateOfBirth = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nam@xxx.edu",
                            FacultyId = "CNTT",
                            FullName = "Đào Ngọc Nam",
                            Gender = "Nam",
                            Hometown = "Hà Nội",
                            PasswordHash = "$2a$11$0v6jC.8f2d.1v.Q7L0.8o.9Q5i.4E1v2d6s.4f2d.1v.Q7L0.8o",
                            Status = "Đang học"
                        },
                        new
                        {
                            MSSV = "18710206",
                            ClassId = "CNTT18-07",
                            DateOfBirth = new DateTime(2001, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lan@xxx.edu",
                            FacultyId = "CNTT",
                            FullName = "Trần Thị Lan",
                            Gender = "Nữ",
                            Hometown = "Hải Phòng",
                            PasswordHash = "$2a$11$0v6jC.8f2d.1v.Q7L0.8o.9Q5i.4E1v2d6s.4f2d.1v.Q7L0.8o",
                            Status = "Đang học"
                        },
                        new
                        {
                            MSSV = "18710207",
                            ClassId = "KT18-01",
                            DateOfBirth = new DateTime(2000, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bach@xxx.edu",
                            FacultyId = "KT",
                            FullName = "Lê Văn Bách",
                            Gender = "Nam",
                            Hometown = "Nam Định",
                            PasswordHash = "$2a$11$0v6jC.8f2d.1v.Q7L0.8o.9Q5i.4E1v2d6s.4f2d.1v.Q7L0.8o",
                            Status = "Đang học"
                        },
                        new
                        {
                            MSSV = "18710208",
                            ClassId = "CNTT18-06",
                            DateOfBirth = new DateTime(2000, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "huy@xxx.edu",
                            FacultyId = "CNTT",
                            FullName = "Phạm Quang Huy",
                            Gender = "Nam",
                            Hometown = "Hà Nội",
                            PasswordHash = "$2a$11$0v6jC.8f2d.1v.Q7L0.8o.9Q5i.4E1v2d6s.4f2d.1v.Q7L0.8o",
                            Status = "Đang học"
                        },
                        new
                        {
                            MSSV = "18710209",
                            ClassId = "KT18-01",
                            DateOfBirth = new DateTime(2001, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ngoc@xxx.edu",
                            FacultyId = "KT",
                            FullName = "Nguyễn Bích Ngọc",
                            Gender = "Nữ",
                            Hometown = "Thái Bình",
                            PasswordHash = "$2a$11$0v6jC.8f2d.1v.Q7L0.8o.9Q5i.4E1v2d6s.4f2d.1v.Q7L0.8o",
                            Status = "Đang học"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Subject", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectCode");

                    b.HasIndex("FacultyId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectCode = "CNPM_01",
                            Credits = 3,
                            FacultyId = "CNTT",
                            SubjectName = "Công nghệ phần mềm"
                        },
                        new
                        {
                            SubjectCode = "CSDL_01",
                            Credits = 3,
                            FacultyId = "CNTT",
                            SubjectName = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            SubjectCode = "LTW_01",
                            Credits = 3,
                            FacultyId = "CNTT",
                            SubjectName = "Lập trình Web"
                        },
                        new
                        {
                            SubjectCode = "TRR_01",
                            Credits = 2,
                            FacultyId = "CB",
                            SubjectName = "Toán rời rạc"
                        },
                        new
                        {
                            SubjectCode = "KTLT_01",
                            Credits = 3,
                            FacultyId = "CNTT",
                            SubjectName = "Kỹ thuật lập trình"
                        },
                        new
                        {
                            SubjectCode = "MMT_01",
                            Credits = 3,
                            FacultyId = "CNTT",
                            SubjectName = "Mạng máy tính"
                        },
                        new
                        {
                            SubjectCode = "KTCT_01",
                            Credits = 2,
                            FacultyId = "KT",
                            SubjectName = "Kinh tế chính trị"
                        },
                        new
                        {
                            SubjectCode = "NLCB_01",
                            Credits = 3,
                            FacultyId = "KT",
                            SubjectName = "Nguyên lý cơ bản"
                        },
                        new
                        {
                            SubjectCode = "VLDC_01",
                            Credits = 2,
                            FacultyId = "CB",
                            SubjectName = "Vật lý đại cương"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = "GV_001",
                            Email = "ptnga@dainam.edu.vn",
                            FacultyId = "CNTT",
                            FullName = "Phạm Thị Tố Nga",
                            Status = "Active"
                        },
                        new
                        {
                            TeacherId = "GV_002",
                            Email = "nva@dainam.edu.vn",
                            FacultyId = "CNTT",
                            FullName = "Nguyễn Văn A",
                            Status = "Active"
                        },
                        new
                        {
                            TeacherId = "GV_003",
                            Email = "tbc@dainam.edu.vn",
                            FacultyId = "CNTT",
                            FullName = "Trần Bảo Châu",
                            Status = "Active"
                        },
                        new
                        {
                            TeacherId = "GV_004",
                            Email = "lma@dainam.edu.vn",
                            FacultyId = "KT",
                            FullName = "Lê Mai Anh",
                            Status = "Active"
                        },
                        new
                        {
                            TeacherId = "GV_005",
                            Email = "ht@dainam.edu.vn",
                            FacultyId = "CB",
                            FullName = "Hoàng Tuấn",
                            Status = "Active"
                        },
                        new
                        {
                            TeacherId = "GV_006",
                            Email = "dqm@dainam.edu.vn",
                            FacultyId = "CK",
                            FullName = "Đinh Quang Minh",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Class", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Faculty", "Faculty")
                        .WithMany("Classes")
                        .HasForeignKey("FacultyId");

                    b.HasOne("StudentManagementSystem.Models.Teacher", null)
                        .WithMany("HomeRoomClasses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.CourseClass", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Subject", "Subject")
                        .WithMany("CourseClasses")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Teacher", "Teacher")
                        .WithMany("CourseClasses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Grade", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Registration", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.CourseClass", "CourseClass")
                        .WithMany("Registrations")
                        .HasForeignKey("CourseClassId");

                    b.HasOne("StudentManagementSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("CourseClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.HasOne("StudentManagementSystem.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Class");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Subject", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Teacher", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.CourseClass", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Faculty", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Subject", b =>
                {
                    b.Navigation("CourseClasses");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Teacher", b =>
                {
                    b.Navigation("CourseClasses");

                    b.Navigation("HomeRoomClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
